name: Build
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build
        run: nix-shell --run rake

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

  push:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Push PNG
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: build-png
          build_dir: build/png
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push SVG
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: build-svg
          build_dir: build/svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push SVGZ
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: build-svgz
          build_dir: build/svgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
